export const paymentErrorMessageMap: Record<string, string> = {
  '10000': 'Pagamento não autorizado por questões de segurança. Tente outro cartão ou forma de pagamento.',
  '10001': 'Número máximo de tentativas excedido. Aguarde alguns minutos antes de tentar novamente.',
  '10002': 'Pagamento não autorizado pelo banco emissor. Entre em contato com seu banco.',
  '10003': 'Dados da transação inválidos. Verifique as informações e tente novamente.',
  '10004': 'Esta transação não é permitida. Entre em contato com o suporte.',
  '20001': 'Entre em contato com a central do seu cartão para autorizar a compra.',
  '20003': 'Saldo ou limite insuficiente. Tente outro cartão ou forma de pagamento.',
  '20007': 'Dados do cartão incorretos. Verifique número, validade e CVV.',
  '20008': 'O parcelamento solicitado não é permitido para este cartão.',
  '20012': 'O valor da transação não é permitido. Tente um valor diferente.',
  '20017': 'Transação não permitida para este cartão. Entre em contato com seu banco.',
  '20018': 'Entre em contato com a central do seu cartão.',
  '20019': 'Falha temporária de comunicação. Tente novamente em alguns instantes.',
  '20039': 'Este cartão não pode ser usado para este tipo de compra.',
  '20101': 'Senha incorreta. Verifique sua senha e tente novamente.',
  '20102': 'Senha inválida. Utilize sua nova senha.',
  '20103': 'Tentativas de senha excedidas. Entre em contato com a central do seu cartão.',
  '20104': 'Valor excede o limite permitido. Entre em contato com seu banco.',
  '20105': 'Quantidade de transações excedida. Entre em contato com seu banco.',
  '20119': 'Erro temporário. Por favor, tente novamente.',
  '20158': 'Pagamento não autorizado no momento. Tente novamente mais tarde.',
  '20159': 'É necessária autenticação adicional para esta compra.',
  '20301': 'Cartão bloqueado. Desbloqueie seu cartão e tente novamente.',
  '20999': 'Erro no processamento. Entre em contato com o suporte.',
};